categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
about: About
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
